# Generated by Django 3.0.6 on 2020-07-20 10:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('category', models.CharField(choices=[('Per', 'Performance'), ('Eve', 'EveryDay'), ('Lon', 'LongBoard'), ('Kit', 'KiteBoard')], max_length=30)),
                ('price', models.FloatField()),
                ('level', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('description', models.TextField(blank=True)),
                ('weight', models.FloatField()),
                ('bigImg', models.CharField(max_length=30)),
                ('smallImg', models.CharField(max_length=30)),
            ],
        ),
    ]
