# Generated by Django 3.0.6 on 2020-07-19 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surf_app', '0003_remove_user_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='myUser',
        ),
    ]
