# Generated by Django 3.0.4 on 2020-07-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surf_app', '0004_auto_20200719_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='fittnes',
            field=models.CharField(choices=[('Po', 'Poor'), ('Av', 'Average'), ('Go', 'Good'), ('Gr', 'Great')], default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myuser',
            name='height',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myuser',
            name='weight',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
