# Generated by Django 3.0.6 on 2020-07-19 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surf_app', '0005_auto_20200719_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='fittnes',
            field=models.CharField(choices=[('Po', 'Poor'), ('Av', 'Average'), ('Go', 'Good'), ('Gr', 'Great')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
