# Generated by Django 3.0.6 on 2020-07-20 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surf_app', '0010_auto_20200720_0742'),
    ]

    operations = [
        migrations.DeleteModel(
            name='myUser',
        ),
    ]
